# Generated by Django 5.2.5 on 2026-06-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('developer', 'Developer'), ('standard', 'Standard User')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='tokens_allocated',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='user',
            name='tokens_used',
            field=models.IntegerField(default=0),
        ),
    ]
