# Generated by Django 5.2.5 on 2026-06-03 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role_user_tokens_allocated_user_tokens_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
