services:
  - type: web
    name: lead-magnet-api
    env: python
    runtime: python-3.10.0

    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      python Backend/scripts/test_db_connection.py

    startCommand: sh Backend/scripts/render_start.sh

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: django_project.settings
      - fromContext: PORT

    healthCheckPath: /api/ping/
