# Generated by Django 5.2.5 on 2026-02-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_magnets', '0006_templateselection_image_upload_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadmagnet',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('error', 'Error'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
