# Generated by Django 5.2.5 on 2026-04-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_magnets', '0008_pdfgenerationjob'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='SystemConfiguration',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('key', models.CharField(max_length=255, unique=True)),
                        ('value', models.TextField()),
                        ('config_type', models.CharField(choices=[('text', 'Plain Text'), ('json', 'JSON Object'), ('html', 'HTML Content')], default='text', max_length=10)),
                        ('description', models.TextField(blank=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'verbose_name': 'System Configuration',
                        'verbose_name_plural': 'System Configurations',
                    },
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    CREATE TABLE IF NOT EXISTS lead_magnets_systemconfiguration (
                        id bigserial PRIMARY KEY,
                        key varchar(255) NOT NULL UNIQUE,
                        value text NOT NULL,
                        config_type varchar(10) NOT NULL,
                        description text NOT NULL DEFAULT '',
                        created_at timestamptz NOT NULL DEFAULT now(),
                        updated_at timestamptz NOT NULL DEFAULT now()
                    );
                    """,
                    reverse_sql="DROP TABLE IF EXISTS lead_magnets_systemconfiguration;"
                )
            ]
        )
    ]
