# Generated by Django 5.2.5 on 2026-04-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_magnets', '0008_systemconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfgenerationjob',
            name='tokens_used',
            field=models.IntegerField(default=0),
        ),
    ]
