# Generated by Django 5.2.5 on 2026-04-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_magnets', '0009_systemconfiguration'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='pdfgenerationjob',
                    name='tokens_used',
                    field=models.IntegerField(default=0),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE lead_magnets_pdfgenerationjob ADD COLUMN IF NOT EXISTS tokens_used integer NOT NULL DEFAULT 0;",
                    reverse_sql="ALTER TABLE lead_magnets_pdfgenerationjob DROP COLUMN IF EXISTS tokens_used;"
                )
            ]
        )
    ]
