# Generated by Django 5.2.5 on 2026-05-15 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead_magnets', '0007_alter_leadmagnet_status'),
        ('lead_magnets', '0009_pdfgenerationjob_tokens_used'),
    ]

    operations = [
    ]
