# Generated by Django 5.2.5 on 2026-05-22 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_magnets', '0010_pdfgenerationjob_tokens_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfgenerationjob',
            name='lead_magnet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdf_jobs', to='lead_magnets.leadmagnet'),
        ),
        migrations.RunSQL(
            sql="ALTER TABLE lead_magnets_pdfgenerationjob ALTER COLUMN lead_magnet_id DROP NOT NULL;",
            reverse_sql="ALTER TABLE lead_magnets_pdfgenerationjob ALTER COLUMN lead_magnet_id SET NOT NULL;"
        ),
    ]
